version: "3"
services:
  #backend:
   # build: ./emissor-os-backend
    #image: emissor-os-backend:latest
  frontend:
    build: ./emissor-os-front
    image: emissor-os-front:latest
    ports: 
      - "80:80"
    #depends_on:
     # - backend